=== marcoslujan/Portfolio_Marcos_Lujan/portfolio/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="proyectos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="proyecto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="img" type="xs:string" minOccurs="0"/>
                            <xs:element name="descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcoslujan/Portfolio_Marcos_Lujan/portfolio/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<proyectos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="data.xsd">
    <proyecto>
        <titulo>Hollow Knight wiki</titulo>
        <img>img/Hollow_Knight_(Verse).webp</img>
        <descripcion>Proyecto en HTML y CSS sobre una Wikipedia del videojuego Metroidvania Hollow Knight </descripcion>
    </proyecto>

     <proyecto>
        <titulo>Colección Dark Souls</titulo>
        <img>img/DarkSoulsLogo.webp</img> 
        <descripcion>Proyecto en HTML, CSS y JavaScript, de colección de juegos de la saga Souls y similares </descripcion>
    </proyecto>

     <proyecto>
        <titulo>Gestor de películas</titulo>
        <img>img/github_logo.webp</img>
        <descripcion>Proyecto de un gestor de peliculas hecho en java</descripcion>
     </proyecto>

     <proyecto>
        <titulo>Gestor de reservas</titulo>
        <img>img/github_logo.webp</img>
        <descripcion>Proyecto de un gestor de reservas hecho en java</descripcion>
    </proyecto>
